# fly.toml app configuration file generated for matchingprocessing on 2023-06-29T21:02:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "matchingprocessing"
primary_region = "fra"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
