# fly.toml app configuration file generated for matchingcomparison on 2023-06-29T23:08:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "matchingcomparison"
primary_region = "fra"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
