# fly.toml app configuration file generated for couragesync on 2023-07-04T01:17:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "couragesync"
primary_region = "fra"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
